# Stage 1: install dependencies and build the TanStack Start app
FROM node:22-alpine AS build
WORKDIR /app

# Copy dependency manifests first so Docker can cache npm install.
COPY package.json package-lock.json ./
RUN npm ci

# Vite inlines VITE_* variables during the build.
ARG VITE_API_BASE_URL=http://localhost:5000
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

COPY . ./
RUN npm run build


# Stage 2: run the production server generated by Nitro
FROM node:22-alpine AS runtime
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOST=0.0.0.0

COPY --from=build /app/.output ./.output

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
